# Generated by Django 5.0.4 on 2024-05-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='is_rented',
            field=models.BooleanField(default=False, verbose_name='Kirada mı'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='weight',
            field=models.FloatField(verbose_name='Ağırlık'),
        ),
    ]
